export const ARTICLES_RECENT_LIST_TILE_COUNT = 6;
export const ARTICLES_RECENT_LIST_REST_COUNT = 6 * 3;
export const ARTICLES_RECENT_LIST_TOTAL_COUNT =
  ARTICLES_RECENT_LIST_TILE_COUNT + ARTICLES_RECENT_LIST_REST_COUNT;
