import { IconTypes } from "./icon-types";
import {
  ArrowChevronLeft,
  ArrowChevronRight,
  ArrowChevronUp,
  ArrowTriangleLeft,
  Bluesky,
  CheckBox,
  Close,
  Copy,
  Dev,
  Download,
  Email,
  Github,
  Goodreads,
  HamburgerMenu,
  Info,
  Like,
  LinkedIn,
  Mastodon,
  Medium,
  OpenInNew,
  ProductHunt,
  Quote,
  Substack,
  Telegram,
  Twitter,
  Website,
  X,
  YouTube,
} from "./svg";

export const ICON_TYPE_SVGS = {
  [IconTypes.ArrowChevronDown]: ArrowTriangleLeft,
  [IconTypes.ArrowChevronLeft]: ArrowChevronLeft,
  [IconTypes.ArrowChevronRight]: ArrowChevronRight,
  [IconTypes.ArrowChevronUp]: ArrowChevronUp,
  [IconTypes.ArrowTriangleLeft]: ArrowTriangleLeft,
  [IconTypes.ArrowTriangleRight]: ArrowTriangleLeft,
  [IconTypes.Bluesky]: Bluesky,
  [IconTypes.CheckBox]: CheckBox,
  [IconTypes.Close]: Close,
  [IconTypes.Copy]: Copy,
  [IconTypes.Dev]: Dev,
  [IconTypes.Download]: Download,
  [IconTypes.Email]: Email,
  [IconTypes.Github]: Github,
  [IconTypes.Goodreads]: Goodreads,
  [IconTypes.HamburgerMenu]: HamburgerMenu,
  [IconTypes.Info]: Info,
  [IconTypes.Like]: Like,
  [IconTypes.LinkedIn]: LinkedIn,
  [IconTypes.Mastodon]: Mastodon,
  [IconTypes.Medium]: Medium,
  [IconTypes.OpenInNew]: OpenInNew,
  [IconTypes.ProductHunt]: ProductHunt,
  [IconTypes.Quote]: Quote,
  [IconTypes.Substack]: Substack,
  [IconTypes.Telegram]: Telegram,
  [IconTypes.Twitter]: Twitter,
  [IconTypes.Website]: Website,
  [IconTypes.X]: X,
  [IconTypes.YouTube]: YouTube,
};
