import { IconTypes } from "./icon-types";
import {
  ArrowChevronDown,
  ArrowChevronLeft,
  ArrowChevronRight,
  ArrowChevronUp,
  ArrowTriangleLeft,
  CheckBox,
  Close,
  Dev,
  Email,
  Github,
  Hamburger,
  Like,
  LinkedIn,
  Mastodon,
  Medium,
  OpenInNew,
  ProductHunt,
  Quote,
  Substack,
  Telegram,
  Twitter,
  Website,
  X,
  YouTube,
} from "./svg";

export const ICON_TYPE_SVGS = {
  [IconTypes.ArrowChevronLeft]: ArrowChevronLeft,
  [IconTypes.ArrowChevronRight]: ArrowChevronRight,
  [IconTypes.ArrowChevronUp]: ArrowChevronUp,
  [IconTypes.ArrowChevronDown]: ArrowChevronDown,
  [IconTypes.ArrowTriangleLeft]: ArrowTriangleLeft,
  [IconTypes.ArrowTriangleRight]: ArrowTriangleLeft,
  [IconTypes.Close]: Close,
  [IconTypes.CheckBox]: CheckBox,
  [IconTypes.Dev]: Dev,
  [IconTypes.Email]: Email,
  [IconTypes.Github]: Github,
  [IconTypes.Hamburger]: Hamburger,
  [IconTypes.LinkedIn]: LinkedIn,
  [IconTypes.Like]: Like,
  [IconTypes.Mastodon]: Mastodon,
  [IconTypes.Medium]: Medium,
  [IconTypes.ProductHunt]: ProductHunt,
  [IconTypes.OpenInNew]: OpenInNew,
  [IconTypes.Quote]: Quote,
  [IconTypes.Substack]: Substack,
  [IconTypes.Telegram]: Telegram,
  [IconTypes.Twitter]: Twitter,
  [IconTypes.Website]: Website,
  [IconTypes.X]: X,
  [IconTypes.YouTube]: YouTube,
};
