import { IconComponent } from "./icon-component";
import { IconType, IconTypes } from "./icon-types";
import {
  ArrowChevronDown,
  ArrowChevronLeft,
  ArrowChevronRight,
  ArrowChevronUp,
  ArrowTriangleLeft,
  ArrowTriangleRight,
  Bluesky,
  CheckBox,
  Close,
  Copy,
  Dev,
  DevTalk,
  Download,
  Email,
  GitHub,
  Goodreads,
  HamburgerMenu,
  Info,
  Like,
  LinkedIn,
  Mastodon,
  Medium,
  OpenInNew,
  Person,
  ProductHunt,
  Quote,
  RationalReminder,
  Reddit,
  Search,
  Signal,
  Substack,
  Telegram,
  Twitter,
  Website,
  Whirlpool,
  X,
  YouTube,
} from "./svg";

export const ICON_TYPE_SVGS: Partial<Record<IconType, IconComponent>> = {
  [IconTypes.ArrowChevronDown]: ArrowChevronDown,
  [IconTypes.ArrowChevronLeft]: ArrowChevronLeft,
  [IconTypes.ArrowChevronRight]: ArrowChevronRight,
  [IconTypes.ArrowChevronUp]: ArrowChevronUp,
  [IconTypes.ArrowTriangleLeft]: ArrowTriangleLeft,
  [IconTypes.ArrowTriangleRight]: ArrowTriangleRight,
  [IconTypes.Bluesky]: Bluesky,
  [IconTypes.CheckBox]: CheckBox,
  [IconTypes.Close]: Close,
  [IconTypes.Copy]: Copy,
  [IconTypes.Dev]: Dev,
  [IconTypes.DevTalk]: DevTalk,
  [IconTypes.Download]: Download,
  [IconTypes.Email]: Email,
  [IconTypes.GitHub]: GitHub,
  [IconTypes.Goodreads]: Goodreads,
  [IconTypes.HamburgerMenu]: HamburgerMenu,
  [IconTypes.Info]: Info,
  [IconTypes.Like]: Like,
  [IconTypes.LinkedIn]: LinkedIn,
  [IconTypes.Mastodon]: Mastodon,
  [IconTypes.Medium]: Medium,
  [IconTypes.OpenInNew]: OpenInNew,
  [IconTypes.Person]: Person,
  [IconTypes.ProductHunt]: ProductHunt,
  [IconTypes.Quote]: Quote,
  [IconTypes.Reddit]: Reddit,
  [IconTypes.RationalReminder]: RationalReminder,
  [IconTypes.Search]: Search,
  [IconTypes.Signal]: Signal,
  [IconTypes.Substack]: Substack,
  [IconTypes.Telegram]: Telegram,
  [IconTypes.Twitter]: Twitter,
  [IconTypes.Website]: Website,
  [IconTypes.Whirlpool]: Whirlpool,
  [IconTypes.X]: X,
  [IconTypes.YouTube]: YouTube,
};
