export const tagTitles: Record<string, string> = {
  ["developer-environment"]: "Dev env",
  ["internationalisation-and-localisation"]: "I11n and L10n",
  ["react-testing-library"]: "RTL",
  ["scss-and-less"]: "SCSS and LESS",
  ai: "AI",
  css: "CSS",
  devops: "DevOps",
  e2e: "E2E",
  fp: "FP",
  html: "HTML",
  nextjs: "NextJS",
  nfr: "NFR",
  nodejs: "NodeJS",
  observability: "Observability",
  oop: "OOP",
  rxjs: "RxJS",
  seo: "SEO",
};
