import type { MDXComponents } from "mdx/types";

import {
  MdxA,
  MdxBlockquote,
  MdxCode,
  MdxH1,
  MdxH2,
  MdxH3,
  MdxH4,
  MdxImg,
  MdxLI,
  MdxOL,
  MdxP,
  MdxPre,
  MdxTBody,
  MdxTHead,
  MdxTable,
  MdxTd,
  MdxTh,
  MdxTr,
  MdxUL,
  MdxWrapper,
} from "./components";

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    a: MdxA,
    blockquote: MdxBlockquote,
    code: MdxCode,
    h1: MdxH1,
    h2: MdxH2,
    h3: MdxH3,
    h4: MdxH4,
    img: MdxImg,
    li: MdxLI,
    ol: MdxOL,
    p: MdxP,
    pre: MdxPre,
    ul: MdxUL,
    table: MdxTable,
    tbody: MdxTBody,
    thead: MdxTHead,
    tr: MdxTr,
    th: MdxTh,
    td: MdxTd,
    wrapper: MdxWrapper,
    ...components,
  };
}
